version: "3.2"

services:

  frontend:
    build: ./images/frontend
    container_name: frontend
    ports:
      - 80:3000
    environment:
      BACKEND_URL: backend

  backend:
    build: ./images/backend
    container_name: backend
    ports:
      - 4000